/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frente;

import java.util.List;
import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Iterator;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author rossi.sebastian2
 */
public class Principal extends javax.swing.JFrame{

    
    private List<File> archivos;
    private Iterator it;
    private File directorio;
    private MiModeloTabla miModeloTabla;
            
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        arbolito();
        archivos = new ArrayList<>();
        
        iniciarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgNumeracion = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        archivosTabla = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        cambiarNombres = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        texfFieldNombre = new javax.swing.JTextField();
        botonCambiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        rbPrincipio = new javax.swing.JRadioButton();
        rbFinal = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        botonCarpeta = new javax.swing.JButton();
        txtFieldCarpeta = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        arbol = new javax.swing.JTree();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuArchivoSalir = new javax.swing.JMenuItem();
        menuOtros = new javax.swing.JMenu();
        menuOtrosAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        archivosTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(archivosTabla);

        jLabel1.setText("Nombre nuevo");

        texfFieldNombre.setText("[Escribir nuevo nombre para los archivos]");
        texfFieldNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texfFieldNombreMouseClicked(evt);
            }
        });

        botonCambiar.setText("Cambiar");
        botonCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiarActionPerformed(evt);
            }
        });

        jLabel2.setText("Numeración");

        bgNumeracion.add(rbPrincipio);
        rbPrincipio.setText("Principio");

        bgNumeracion.add(rbFinal);
        rbFinal.setText("Final");

        javax.swing.GroupLayout cambiarNombresLayout = new javax.swing.GroupLayout(cambiarNombres);
        cambiarNombres.setLayout(cambiarNombresLayout);
        cambiarNombresLayout.setHorizontalGroup(
            cambiarNombresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cambiarNombresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cambiarNombresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(cambiarNombresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cambiarNombresLayout.createSequentialGroup()
                        .addComponent(rbPrincipio)
                        .addGap(64, 64, 64)
                        .addComponent(rbFinal))
                    .addComponent(texfFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 410, Short.MAX_VALUE)
                .addComponent(botonCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        cambiarNombresLayout.setVerticalGroup(
            cambiarNombresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cambiarNombresLayout.createSequentialGroup()
                .addGroup(cambiarNombresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cambiarNombresLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cambiarNombresLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(cambiarNombresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(texfFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(cambiarNombresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(rbPrincipio)
                            .addComponent(rbFinal))))
                .addGap(133, 133, 133))
        );

        jTabbedPane1.addTab("Cambiar nombre de archivos", cambiarNombres);

        botonCarpeta.setText("Elegir carpeta");
        botonCarpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarpetaActionPerformed(evt);
            }
        });

        txtFieldCarpeta.setText("[Dirección de la carpeta donde estan los archivos a modificar el nombre]");
        txtFieldCarpeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFieldCarpetaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(txtFieldCarpeta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCarpeta, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCarpeta)
                    .addComponent(txtFieldCarpeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(arbol);

        menuArchivo.setText("Archivo");

        menuArchivoSalir.setText("Salir");
        menuArchivoSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArchivoSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(menuArchivoSalir);

        jMenuBar1.add(menuArchivo);

        menuOtros.setText("Otros");

        menuOtrosAcerca.setText("Acerca...");
        menuOtrosAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOtrosAcercaActionPerformed(evt);
            }
        });
        menuOtros.add(menuOtrosAcerca);

        jMenuBar1.add(menuOtros);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * @param evt 
     */
    private void botonCarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarpetaActionPerformed
        if(seleccionadorCarpeta()){
            miModeloTabla.setLista(archivos); //carga tabla
            txtFieldCarpeta.setText(directorio.getPath()+"\\");
        }
        else
            txtFieldCarpeta.setText("");
    }//GEN-LAST:event_botonCarpetaActionPerformed

    
    
    
    private void botonCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiarActionPerformed
        if(cambiarNombre(texfFieldNombre.getText())){
            iniciarTabla();
            miModeloTabla.setLista(archivos); //carga tabla
            texfFieldNombre.setText("[Escribir nuevo nombre para los archivos]");
        }
    }//GEN-LAST:event_botonCambiarActionPerformed

    
    
    private void txtFieldCarpetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldCarpetaMouseClicked
        if(seleccionadorCarpeta()){
            miModeloTabla.setLista(archivos); //carga tabla
            txtFieldCarpeta.setText(directorio.getPath()+"\\");
        }
        else
            txtFieldCarpeta.setText("[Dirección de la carpeta donde estan los archivos a modificar el nombre]");
    }//GEN-LAST:event_txtFieldCarpetaMouseClicked

    private void texfFieldNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texfFieldNombreMouseClicked
        texfFieldNombre.setText("");
    }//GEN-LAST:event_texfFieldNombreMouseClicked

    private void menuArchivoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArchivoSalirActionPerformed
        salir();
    }//GEN-LAST:event_menuArchivoSalirActionPerformed

    private void menuOtrosAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOtrosAcercaActionPerformed
        mensaje("Carnotaurus es re copado!", "Sebi!");
    }//GEN-LAST:event_menuOtrosAcercaActionPerformed

    

    /**************************************************************************/
    
    /**
     * Pone la tabla en 0 y le agrega los titulos
     */
    private void iniciarTabla(){
        miModeloTabla = new MiModeloTabla();
        miModeloTabla.setLista(archivos);
        archivosTabla.setModel(miModeloTabla);
    }
    
    
    /**
     * Metodo para seleccionar la carpeta
     * @return false si se cancela el file chooser
     */
    private boolean seleccionadorCarpeta(){
        archivos = new ArrayList<>();
        JFileChooser jf = new JFileChooser();
        jf.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if(JFileChooser.APPROVE_OPTION == jf.showOpenDialog(this)) {
            iniciarTabla();
            directorio = jf.getSelectedFile();
            archivos.addAll(Arrays.asList(directorio.listFiles()));
            rbPrincipio.setSelected(rootPaneCheckingEnabled);
            return true;
        }
        else
            return false;
            
    }

    
    /**
     * Metodo para cambiar de nombre de todos los archivos de la carpeta
     * @param nombreBase nombre en comun de todos los archivos
     * @return 
     */
    private boolean cambiarNombre(String nombreBase){
        if(archivos.isEmpty()){
            mensaje("No seleccionaste carpeta!", "Muy mal.");
            return false;
        }
        
        if(nombreBase.equals("[Escribir nuevo nombre para los archivos]") || nombreBase.equals("")){
            mensaje("Hay que escribir un nombre!", "Asi no, che.");
            return false;
        }
        
        
        List<File> aux = new ArrayList<>();
        String nuevoNombre;
        int numero = 0;
        
        it = archivos.iterator();
        
        while(it.hasNext()){
            
            File viejo = (File)it.next();
            
            if(!viejo.isDirectory()){
                String ext = viejo.getName().substring(viejo.getName().indexOf('.'), viejo.getName().length());
                
                if(rbPrincipio.isSelected())
                    nuevoNombre=directorio+"/"+Integer.toString(numero)+"-"+nombreBase+ext;
                else
                    nuevoNombre=directorio+"/"+nombreBase+"-"+Integer.toString(numero)+ext;
                File nuevo = new File(nuevoNombre);
                viejo.renameTo(nuevo);
                aux.add(nuevo);
                numero++;
                it.remove();
                nuevoNombre="";
            }
            
        }
        
        Iterator itaux = aux.iterator();
        while(itaux.hasNext()){
            archivos.add((File)itaux.next());
            itaux.remove();
        }
        return true;
    }
    
    /**
     * Ventana de mensaje
     * @param mensaje
     * @param titulo 
     */
    private void mensaje(String mensaje, String titulo)
    {
        Icon icono = new ImageIcon(getClass().getResource("/frente/dino.png"));
        JOptionPane.showMessageDialog(null, mensaje, titulo, JOptionPane.INFORMATION_MESSAGE, icono);
    }
    
    
    private void salir(){
        System.exit(0);
    }
    
    /**
     * TODO: Hacer su propia clase
     */
    private void arbolito(){
        File carpota = new File("/");
        //Creamos el nodo raíz y el DefaultTreeModel
        DefaultMutableTreeNode principal = new DefaultMutableTreeNode("Archivos");
        DefaultTreeModel modelo;
        //Este nodo lo usaremos para ir agregando archivos al nodo principal
        DefaultMutableTreeNode nodo;
        //Creamos un array de archivos a partir de los archivos del directorio
        File[] listaArchivos = carpota.listFiles();
        //Este for recorrerá "listaArchivos" mientras haya un archivo siguiente
        for (File listaArchivo : listaArchivos) {
             //Creamos un nodo con el nombre del archivo en el que estamos y se lo agregamos al nodo raíz
             nodo = new DefaultMutableTreeNode(listaArchivo.getName());
             principal.add(nodo);
        }
        //Creamos el modelo y se lo asignamos al jTree
        modelo = new DefaultTreeModel(principal, true);
        arbol.setModel(modelo);
    }
    
    /**************************************************************************/
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Principal().setVisible(true);
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbol;
    private javax.swing.JTable archivosTabla;
    private javax.swing.ButtonGroup bgNumeracion;
    private javax.swing.JButton botonCambiar;
    private javax.swing.JButton botonCarpeta;
    private javax.swing.JPanel cambiarNombres;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuItem menuArchivoSalir;
    private javax.swing.JMenu menuOtros;
    private javax.swing.JMenuItem menuOtrosAcerca;
    private javax.swing.JRadioButton rbFinal;
    private javax.swing.JRadioButton rbPrincipio;
    private javax.swing.JTextField texfFieldNombre;
    private javax.swing.JTextField txtFieldCarpeta;
    // End of variables declaration//GEN-END:variables
}
